/*
 * This source file was generated by the Gradle 'init' task
 */
package db_lab;

import static org.assertj.core.api.Assertions.*;

import db_lab.data.dataentity.Product;
import db_lab.data.dataentity.ProductPreview;
import db_lab.model.Model;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Savepoint;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public final class AppTest {

}